package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/cosmo-wise/axle/internal/openapi"
	"github.com/cosmo-wise/axle/internal/schema"
	"github.com/cosmo-wise/axle/pkg/axle"
)

const header = "// Code generated by axle gen; DO NOT EDIT.\n"

// GeneratedFile is an in-memory deterministic generated artifact.
type GeneratedFile struct {
	Path    string
	Content string
}

// Generate returns deterministic generated files for a descriptor.
func Generate(desc axle.Descriptor) ([]GeneratedFile, []axle.Diagnostic) {
	routes := BuildRoutes(desc)
	openapiJSON, err := openapi.Build(desc, routes)
	if err != nil {
		return nil, []axle.Diagnostic{{Code: "AXLE_OPENAPI_BUILD", Path: "openapi.gen.json", Message: err.Error(), SuggestedFix: "Fix route metadata so OpenAPI can be generated."}}
	}
	packageName := desc.Generated.Package
	files := []GeneratedFile{
		{Path: "registry.gen.go", Content: formatGo(renderRegistry(packageName, desc))},
		{Path: "routes.gen.go", Content: formatGo(renderRoutes(packageName, routes))},
		{Path: "types.gen.go", Content: formatGo(renderTypes(packageName, desc))},
		{Path: "openapi.gen.json", Content: openapiJSON},
		{Path: filepath.ToSlash(filepath.Join("migrations", "001_create_"+desc.Resource.Table+".sql")), Content: renderMigration(desc)},
	}
	sort.Slice(files, func(i, j int) bool { return files[i].Path < files[j].Path })
	return files, nil
}

// Write writes generated files under outDir.
func Write(outDir string, files []GeneratedFile) error {
	for _, file := range files {
		path := filepath.Join(outDir, filepath.FromSlash(file.Path))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, []byte(file.Content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

// Check compares generated files against existing files without writing.
func Check(outDir string, files []GeneratedFile) []axle.Diagnostic {
	var diagnostics []axle.Diagnostic
	for _, file := range files {
		path := filepath.Join(outDir, filepath.FromSlash(file.Path))
		existing, err := os.ReadFile(path)
		if err != nil {
			diagnostics = append(diagnostics, axle.Diagnostic{Code: "AXLE_GENERATED_MISSING", Path: path, Message: err.Error(), SuggestedFix: "Run axle gen to create generated files."})
			continue
		}
		if !bytes.Equal(existing, []byte(file.Content)) {
			diagnostics = append(diagnostics, axle.Diagnostic{Code: "AXLE_GENERATED_STALE", Path: path, Message: "generated file does not match descriptor output", SuggestedFix: "Run axle gen and do not hand-edit generated files."})
		}
	}
	return diagnostics
}

func renderRoutes(packageName string, routes []axle.RouteDescriptor) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package " + packageName + "\n\n")
	b.WriteString("import \"github.com/cosmo-wise/axle/pkg/axle\"\n\n")
	b.WriteString("var Routes = []axle.RouteDescriptor{\n")
	for _, route := range routes {
		b.WriteString("\t{\n")
		b.WriteString(fmt.Sprintf("\t\tName: %q,\n", route.Name))
		b.WriteString(fmt.Sprintf("\t\tKind: %q,\n", route.Kind))
		b.WriteString(fmt.Sprintf("\t\tTransportMethod: %q,\n", route.TransportMethod))
		b.WriteString(fmt.Sprintf("\t\tPath: %q,\n", route.Path))
		b.WriteString("\t\tParams: []string{")
		for i, param := range route.Params {
			if i > 0 {
				b.WriteString(", ")
			}
			b.WriteString(fmt.Sprintf("%q", param))
		}
		b.WriteString("},\n")
		b.WriteString(fmt.Sprintf("\t\tRequest: %q,\n", route.Request))
		b.WriteString(fmt.Sprintf("\t\tResponse: %q,\n", route.Response))
		b.WriteString(fmt.Sprintf("\t\tPolicy: %q,\n", route.Policy))
		b.WriteString(fmt.Sprintf("\t\tHandler: %q,\n", route.Handler))
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func renderRegistry(packageName string, desc axle.Descriptor) string {
	var b strings.Builder
	b.WriteString(header)
	b.WriteString("package " + packageName + "\n\n")
	b.WriteString("import \"github.com/cosmo-wise/axle/pkg/axle\"\n\n")
	b.WriteString(fmt.Sprintf("const ResourceName = %q\n", desc.Resource.Name))
	b.WriteString(fmt.Sprintf("const ResourceTable = %q\n", desc.Resource.Table))
	b.WriteString(fmt.Sprintf("const ResourcePath = %q\n\n", desc.Resource.Path))
	b.WriteString("var ResourceDescriptor = axle.ResourceDescriptor{\n")
	b.WriteString(fmt.Sprintf("\tName: %q,\n", desc.Resource.Name))
	b.WriteString(fmt.Sprintf("\tPath: %q,\n", desc.Resource.Path))
	b.WriteString(fmt.Sprintf("\tTable: %q,\n", desc.Resource.Table))
	b.WriteString(fmt.Sprintf("\tID: %q,\n", desc.Resource.ID))
	b.WriteString("\tFields: []axle.FieldDescriptor{\n")
	for _, field := range desc.Resource.Fields {
		b.WriteString("\t\t{")
		renderFieldDescriptor(&b, field)
		b.WriteString("},\n")
	}
	b.WriteString("\t},\n")
	b.WriteString("\tOperations: []axle.OperationDescriptor{\n")
	for _, op := range desc.Resource.Operations {
		renderOperation(&b, op)
	}
	b.WriteString("\t},\n")
	if len(desc.Resource.Actions) > 0 {
		b.WriteString("\tActions: []axle.OperationDescriptor{\n")
		for _, op := range desc.Resource.Actions {
			renderOperation(&b, op)
		}
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n\n")
	if descriptorNeedsBoolPtr(desc.Resource) {
		b.WriteString("func boolPtr(value bool) *bool { return &value }\n\n")
	}
	b.WriteString("var ResourceRegistry = axle.ResourceRegistry{Resource: ResourceDescriptor, Routes: Routes}\n")
	b.WriteString("var Catalog = axle.Catalog{Resources: []axle.ResourceRegistry{ResourceRegistry}}\n")
	return b.String()
}

func descriptorNeedsBoolPtr(resource axle.ResourceDescriptor) bool {
	for _, field := range resource.Fields {
		if field.Nullable != nil {
			return true
		}
	}
	return false
}

func renderFieldDescriptor(b *strings.Builder, field axle.FieldDescriptor) {
	b.WriteString(fmt.Sprintf("Name: %q, Type: %q, Mutable: %t", field.Name, field.Type, field.Mutable))
	if field.Nullable != nil {
		b.WriteString(fmt.Sprintf(", Nullable: boolPtr(%t)", *field.Nullable))
	}
	if field.Unique {
		b.WriteString(", Unique: true")
	}
	if field.Index {
		b.WriteString(", Index: true")
	}
	if field.Auto != "" {
		b.WriteString(fmt.Sprintf(", Auto: %q", field.Auto))
	}
	if field.Default != "" {
		b.WriteString(fmt.Sprintf(", Default: %q", field.Default))
	}
	if field.References != nil {
		b.WriteString(", References: &axle.ReferenceDescriptor{")
		if field.References.Resource != "" {
			b.WriteString(fmt.Sprintf("Resource: %q, ", field.References.Resource))
		}
		b.WriteString(fmt.Sprintf("Table: %q", field.References.Table))
		if field.References.Field != "" {
			b.WriteString(fmt.Sprintf(", Field: %q", field.References.Field))
		}
		if field.References.OnDelete != "" {
			b.WriteString(fmt.Sprintf(", OnDelete: %q", field.References.OnDelete))
		}
		b.WriteString("}")
	}
}

func renderOperation(b *strings.Builder, op axle.OperationDescriptor) {
	b.WriteString("\t\t{\n")
	b.WriteString(fmt.Sprintf("\t\t\tName: %q,\n", op.Name))
	b.WriteString(fmt.Sprintf("\t\t\tKind: %q,\n", op.Kind))
	if op.Path != "" {
		b.WriteString(fmt.Sprintf("\t\t\tPath: %q,\n", op.Path))
	}
	b.WriteString(fmt.Sprintf("\t\t\tRequest: %q,\n", op.Request))
	b.WriteString(fmt.Sprintf("\t\t\tResponse: %q,\n", op.Response))
	b.WriteString(fmt.Sprintf("\t\t\tPolicy: %q,\n", op.Policy))
	b.WriteString(fmt.Sprintf("\t\t\tHandler: %q,\n", op.Handler))
	b.WriteString("\t\t},\n")
}

func renderMigration(desc axle.Descriptor) string {
	var b strings.Builder
	b.WriteString("-- Code generated by axle gen; DO NOT EDIT.\n")
	b.WriteString("CREATE TABLE IF NOT EXISTS " + schema.MustQuoteIdent(desc.Resource.Table) + " (\n")
	for i, field := range desc.Resource.Fields {
		column, err := schema.ColumnDefinition(desc.Resource, field, true)
		if err != nil {
			panic(err)
		}
		b.WriteString("  " + column)
		if i < len(desc.Resource.Fields)-1 {
			b.WriteString(",")
		}
		b.WriteString("\n")
	}
	b.WriteString(");\n")
	indexes, err := schema.IndexStatements(desc.Resource)
	if err != nil {
		panic(err)
	}
	for _, statement := range indexes {
		b.WriteString(statement + ";\n")
	}
	return b.String()
}

func formatGo(src string) string {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		return src
	}
	return string(formatted)
}
