// Code generated by axle gen; DO NOT EDIT.
package catalog

import (
	"github.com/cosmo-wise/axle/pkg/axle"
	policies "github.com/cosmo-wise/axle/testdata/examples/generated-backend/descriptors/policies/generated"
	resources "github.com/cosmo-wise/axle/testdata/examples/generated-backend/descriptors/resources/generated"
)

var Catalog = axle.Catalog{Resources: []axle.ResourceRegistry{
	policies.ResourceRegistry,
	resources.ResourceRegistry,
}}
